logging:
  level:
    org.springframework: INFO

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html, text/xml, text/plain, text/css, application/javascript, application/json
    min-response-size: 1024

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://ibin-backend-service-registry:8080/eureka/

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        encoder: feign.jackson.JacksonDecoder
        decoder: feign.jackson.JacksonEncoder