spring:
  data:
    mongodb:
      database: "instruments"
      host: ibin-mongodb
      port: 27017
  profiles:
    active: production
application:
  document-parser:
    fail-on-unknown-attribute: false
